# Generated by Django 4.1.1 on 2022-09-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='nombre_apellido',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre_Apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre y Apellido'),
        ),
    ]
