# Generated by Django 4.1.1 on 2022-10-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('nombre_Apellido', models.CharField(blank=True, max_length=100, verbose_name='Nombre y Apellido')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='misRutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Usuario', max_length=100)),
                ('nombre', models.CharField(default='Nombre', max_length=200, verbose_name='nombre')),
                ('ubicacion', models.TextField(default='url-ubicacion')),
                ('precio', models.TextField(default='precio')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('amazonica', 'Amazoníca'), ('andina', 'Andina'), ('caribe', 'Caribe'), ('orinoquia', 'Orinoquía'), ('pacifica', 'Pacífica')], max_length=9)),
                ('imagen', models.TextField(default='url_imagen')),
            ],
        ),
        migrations.CreateModel(
            name='sitioTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('region', models.CharField(choices=[('amazonica', 'Amazoníca'), ('andina', 'Andina'), ('caribe', 'Caribe'), ('orinoquia', 'Orinoquía'), ('pacifica', 'Pacífica')], max_length=9)),
                ('imagen', models.TextField(default='url-imagen')),
                ('description', models.TextField(default='descripcion sitio')),
                ('video', models.TextField(default='url-video')),
                ('ubicacion', models.TextField(default='url-ubicacion')),
                ('precio', models.TextField(default='precio')),
                ('sitioFavorito', models.BooleanField(default=False)),
            ],
        ),
    ]
